### ISSUE TITLE
NoMethodError extract_options! rails/activesupport dependency? 

### ISSUE THREAD

**Issue by rdalin82** [kristianmandrup/sweetloader#1]
I ran into a problem using this with geo-distance when I start up my sinatra app.  Below is the stack trace.  I am using Ruby 2.2.1, geo-distance, and Sinatra.  I think extract_options! is an activesupport method that usually gets included with rails, but isn't with sinatra.  I added activesupport to my gemfile and required it in my app.rb and that seems to work now.    

`/home/rdalin/.rvm/gems/ruby-2.2.1/gems/sweetloader-0.1.6/lib/sweetloader.rb:21:in`autoload_modules': undefined method `extract_options!' for [:Constants, :Converter, :Maps, :Numeric]:Array (NoMethodError)
    from /home/rdalin/.rvm/gems/ruby-2.2.1/gems/geo_units-0.3.3/lib/geo_units.rb:22:in`module:GeoUnits'
    from /home/rdalin/.rvm/gems/ruby-2.2.1/gems/geo_units-0.3.3/lib/geo_units.rb:21:in `<top (required)>'
    from /home/rdalin/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in`require'
    from /home/rdalin/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /home/rdalin/.rvm/gems/ruby-2.2.1/gems/geo_calc-0.7.8/lib/geo_calc.rb:1:in`<top (required)>'
    from /home/rdalin/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /home/rdalin/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in`require'
    from /home/rdalin/.rvm/gems/ruby-2.2.1/gems/geo_point-0.2.6/lib/geo_point.rb:2:in `<top (required)>'
    from /home/rdalin/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in`require'
    from /home/rdalin/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /home/rdalin/.rvm/gems/ruby-2.2.1/gems/geo-distance-0.2.2/lib/geo-distance.rb:1:in`<top (required)>'
    from /home/rdalin/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
    from /home/rdalin/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in`rescue in require'
    from /home/rdalin/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
    from app.rb:7:in`<main>'`

**Comment by kristianmandrup** [comment]
Great! Good point! There should be a note about that in sweetloader. Ideally that dependency should be removed and all
The geo gems should be decoupled requiring only interfaces and should use dependency injection instead.
